print("Tạo một cái pull request và merge request")
print("Tạo một cái nội dung cho pull request")
print("Tìm hiểu reset and revert")
print("Nội dung cho revert")
print("Cần thêm nội dung cho revert")
print("Hom nay ngay 25/11/2024")
